name: Clickpack submission
description: Upload a Geometry Dash clickpack directly to ClickpackDB
title: "[Clickpack] "
labels: ["clickpack"]
body:
  - type: input
    id: name
    attributes:
      label: Clickpack name
      placeholder: "e.g. Hator Icefall Up Arrow Key"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      placeholder: "Your username"
    validations:
      required: true

  - type: textarea
    id: upload
    attributes:
      label: Upload your clickpack ZIP
      description: |
        Drag & drop your **.zip file** into this box.
        No external links needed.
      placeholder: "Drop the ZIP file here"
    validations:
      required: true

  - type: checkboxes
    id: extras
    attributes:
      label: Extra files
      options:
        - label: Contains noise.wav

  - type: textarea
    id: readme
    attributes:
      label: Description / README
      placeholder: "Optional description"
