name: Clickpack submission
description: Submit a Geometry Dash clickpack to ClickpackDB
title: "[Clickpack] "
labels: ["clickpack"]
body:
  - type: input
    id: name
    attributes:
      label: Clickpack name
      description: The name that will appear on the site
      placeholder: "e.g. Hator Icefall Up Arrow Key"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: Your username or name
      placeholder: "e.g. JasperSoosaar25"
    validations:
      required: true

  - type: input
    id: download
    attributes:
      label: Download URL (zip)
      description: >
        A direct ZIP file URL.
        GitHub raw links, GitHub Releases, or Cloudflare R2 links are supported.
        This file will be re-hosted automatically by ClickpackDB.
      placeholder: "https://raw.githubusercontent.com/.../clickpack.zip"
    validations:
      required: true

  - type: checkboxes
    id: extras
    attributes:
      label: Extra files
      description: Check if your clickpack contains additional files
      options:
        - label: Contains noise.wav
          required: false

  - type: textarea
    id: readme
    attributes:
      label: Description / README
      description: Optional description shown in the database
      placeholder: "Anything we should know about this clickpack?"
